version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: monetra_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: monetra
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - monetra_net

  user_service:
    build: ./user_service
    container_name: monetra_user_service
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - ./user_service/.env
    depends_on:
      - mysql
    volumes:
      - ./user_service:/app
    networks:
      - monetra_net

  reservation_service:    
    build: ./reservation_service
    container_name: monetra_reservation_service
    restart: always
    ports:
      - "5002:5002"
    env_file:
      - ./reservation_service/.env
    depends_on:
      - mysql
    volumes:
      - ./reservation_service:/app
    networks:
      - monetra_net

volumes:
  mysql_data:

networks:
  monetra_net:
    driver: bridge